package name.sitorhy.server.model.playlist.songs;

import java.util.ArrayList;

public class Cdlist{
    public String disstid;
    public long dir_show;
    public long owndir;
    public long dirid;
    public String coveradurl;
    public long dissid;
    public String login;
    public String uin;
    public String encrypt_uin;
    public String dissname;
    public String logo;
    public String pic_mid;
    public String album_pic_mid;
    public long pic_dpi;
    public long isAd;
    public String desc;
    public long ctime;
    public long mtime;
    public String headurl;
    public String ifpicurl;
    public String nick;
    public String nickname;
    public long type;
    public long singerid;
    public String singermid;
    public long isvip;
    public long isdj;
    public ArrayList<Object> tags;
    public long songnum;
    public String songids;
    public String songtypes;
    public long disstype;
    public String dir_pic_url2;
    public long song_update_time;
    public long song_update_num;
    public long total_song_num;
    public long song_begin;
    public long cur_song_num;
    public ArrayList<Songlist> songlist;
    public long visitnum;
    public long cmtnum;
    public long buynum;
    public String scoreavage;
    public long scoreusercount;
}
